#requires -Version 5.1
<#
  Test-RuleCatalog.ps1  --  proves rules/catalog.json is a faithful, safe representation of the
  rules that both removal scripts actually define.

  PURELY STATIC, like Test-PuaRules.ps1: the rules are read out of the scripts through the
  PowerShell AST with SafeGetValue(). Nothing is executed, nothing is removed, and there is no
  registry, filesystem, process or network access.

  This is the SEMANTIC half of the phase-1 safety net. The syntactic half is
  scripts/compile-rules.py --check, which compares generated bytes against the scripts. The two
  are independent: this test catches a compiler that emits valid-but-wrong PowerShell, and the
  compiler check catches a catalog that has drifted from the shipped text.

  What it enforces:
    1. FIDELITY - catalog.json matches the AST of BOTH scripts, field by field.
    2. SAFETY   - Name is long enough for an unconditional sweep, Aliases carry evidence,
                  hashes are lowercase 64-hex, Names are unique and not benign software.
    3. BENIGN   - benign.json still mirrors the corpora inside Test-PuaRules.ps1.

  Exit code 0 = pass, 1 = failure.
#>
param([string]$RepoRoot = (Split-Path -Parent $PSScriptRoot))

$ErrorActionPreference = 'Stop'

$Hosted      = Join-Path $RepoRoot 'hosted-removal.ps1'
$Local       = Join-Path $RepoRoot 'PUAKILLER-LOCAL.ps1'
$TestPuaRule = Join-Path $RepoRoot 'tests\Test-PuaRules.ps1'
$CatalogPath = Join-Path $RepoRoot 'rules\catalog.json'
$BenignPath  = Join-Path $RepoRoot 'rules\benign.json'

# --- AST extraction: identical mechanism to Test-PuaRules.ps1 ---------------
function Get-ScriptVar {
    param([string]$Path, [string]$VarName)
    if (-not (Test-Path -LiteralPath $Path)) { throw "script not found: $Path" }
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$null, [ref]$null)
    $hit = $ast.FindAll({
        param($n)
        $n -is [System.Management.Automation.Language.AssignmentStatementAst] -and
        $n.Left -is [System.Management.Automation.Language.VariableExpressionAst] -and
        $n.Left.VariablePath.UserPath -eq $VarName
    }, $true) | Select-Object -First 1
    if (-not $hit) { throw "variable `$$VarName not found in $(Split-Path -Leaf $Path)" }
    $expr = $hit.Right
    if ($expr -is [System.Management.Automation.Language.PipelineAst])          { $expr = $expr.PipelineElements[0] }
    if ($expr -is [System.Management.Automation.Language.CommandExpressionAst]) { $expr = $expr.Expression }
    return $expr.SafeGetValue()
}

# ConvertTo-Json collapses a one-element array into a bare scalar, so every array field read
# back out of the catalog has to be re-widened. Same normalisation the Python compiler does in
# as_list(); keeping both sides explicit avoids a whole class of silent mismatches.
function AsArray($Value) {
    if ($null -eq $Value) { return @() }
    return @($Value)
}

function Join-Values($Value) { return ((AsArray $Value) -join '|') }

$script:fail = 0; $script:pass = 0
function Check($cond, $msg) {
    if ($cond) { $script:pass++ } else { $script:fail++; Write-Host "  [FAIL] $msg" -ForegroundColor Red }
}

# --- load -------------------------------------------------------------------
Check (Test-Path -LiteralPath $CatalogPath) 'rules/catalog.json is missing'
Check (Test-Path -LiteralPath $BenignPath)  'rules/benign.json is missing'
if ($script:fail) { Write-Host 'RESULT: FAIL (catalog files missing)' -ForegroundColor Red; exit 1 }

$catalog = Get-Content -LiteralPath $CatalogPath -Raw | ConvertFrom-Json
$benign  = Get-Content -LiteralPath $BenignPath  -Raw | ConvertFrom-Json

$catalogRules = AsArray $catalog.rules
Write-Host "Loaded $($catalogRules.Count) catalog rules, $((AsArray $catalog.bad_signers).Count) signers" -ForegroundColor DarkGray

# ===========================================================================
#  1. FIDELITY - the catalog must match what BOTH scripts actually define
# ===========================================================================
Write-Host "`n== FIDELITY: catalog matches the AST of both scripts ==" -ForegroundColor Cyan

$scalarFields = @('Name', 'Label', 'Rx', 'Pub')
$arrayFields  = @('Proc', 'Harden', 'Aliases', 'RegNames', 'Hashes')

foreach ($scriptPath in @($Hosted, $Local)) {
    $leaf = Split-Path -Leaf $scriptPath
    $live = @(Get-ScriptVar -Path $scriptPath -VarName 'Puas')

    Check ($live.Count -eq $catalogRules.Count) "$leaf defines $($live.Count) rules, catalog has $($catalogRules.Count)"
    if ($live.Count -ne $catalogRules.Count) { continue }

    for ($i = 0; $i -lt $live.Count; $i++) {
        $l = $live[$i]
        $c = $catalogRules[$i]
        foreach ($f in $scalarFields) {
            Check ([string]$l[$f] -ceq [string]$c.$f) "$leaf rule #${i} ${f}: script='$($l[$f])' catalog='$($c.$f)'"
        }
        Check ([bool]$l['Nw'] -eq [bool]$c.Nw) "$leaf rule #${i} Nw: script='$($l['Nw'])' catalog='$($c.Nw)'"
        foreach ($f in $arrayFields) {
            Check ((Join-Values $l[$f]) -ceq (Join-Values $c.$f)) "$leaf rule #${i} ${f}: script='$(Join-Values $l[$f])' catalog='$(Join-Values $c.$f)'"
        }
    }

    $liveSigners = AsArray (Get-ScriptVar -Path $scriptPath -VarName 'BadSigners')
    Check (($liveSigners -join ',') -ceq ((AsArray $catalog.bad_signers) -join ',')) "$leaf `$BadSigners differs from the catalog"
}

# ===========================================================================
#  2. SAFETY - structural guards the catalog must keep true
# ===========================================================================
Write-Host '== SAFETY: catalog invariants ==' -ForegroundColor Cyan

$benignNames = AsArray $benign.names
$seen = @{}

foreach ($c in $catalogRules) {
    $name = [string]$c.Name

    # Name drives an UNCONDITIONAL folder sweep (hosted-removal.ps1:1050-1062). Aliases are
    # only removed when static evidence is found inside (Test-PuaAliasDir). Keeping that
    # asymmetry intact is invariant I15 in docs/ai-intel/baseline.md.
    Check ($name.Length -ge 5) "Name '$name' is too short for an unconditional folder sweep"
    Check (-not ($benignNames | Where-Object { $_ -ieq $name })) "Name '$name' collides with the benign corpus"

    $key = $name.ToLowerInvariant()
    Check (-not $seen.ContainsKey($key)) "duplicate Name '$name'"
    $seen[$key] = $true

    foreach ($h in (AsArray $c.Hashes)) {
        Check ($h -cmatch '^[0-9a-f]{64}$') "rule '$($c.id)' hash '$h' is not lowercase 64-hex; a malformed hash silently disables the alias guard"
    }

    if ((AsArray $c.Aliases).Count -gt 0) {
        $hasEvidence = ((AsArray $c.Hashes).Count -gt 0) -or ((AsArray $c.Proc).Count -gt 0) -or ([string]$c.Pub)
        Check $hasEvidence "rule '$($c.id)' has Aliases but no Hashes/Proc/Pub evidence to guard them with"
    }

    Check ([string]$c.id -cmatch '^[a-z0-9][a-z0-9-]{1,63}$') "rule id '$($c.id)' is not a stable lowercase slug"
}

# The provenance comments carry the safety rationale. Losing them during a regeneration would
# be a failed migration, not a cosmetic regression (baseline.md R6). Seven of the eleven rules
# shipped with an analysis block (the four oldest entries never had one); that is the floor.
$withLead = @($catalogRules | Where-Object { (AsArray $_.lead).Count -gt 0 })
Check ($withLead.Count -ge 7) "only $($withLead.Count) rules kept their provenance comment block (expected at least 7)"

# ===========================================================================
#  3. BENIGN - benign.json still mirrors the corpora inside the test
# ===========================================================================
Write-Host '== BENIGN: mirror of the corpora in Test-PuaRules.ps1 ==' -ForegroundColor Cyan

$liveNames = AsArray (Get-ScriptVar -Path $TestPuaRule -VarName 'BENIGN_NAMES')
$liveProcs = AsArray (Get-ScriptVar -Path $TestPuaRule -VarName 'BENIGN_PROCS')
$livePubs  = AsArray (Get-ScriptVar -Path $TestPuaRule -VarName 'BENIGN_PUBLISHERS')

Check (($liveNames -join ',') -ceq ((AsArray $benign.names) -join ','))       'benign.json names drifted from $BENIGN_NAMES'
Check (($liveProcs -join ',') -ceq ((AsArray $benign.processes) -join ','))   'benign.json processes drifted from $BENIGN_PROCS'
Check (($livePubs  -join ',') -ceq ((AsArray $benign.publishers) -join ',')) 'benign.json publishers drifted from $BENIGN_PUBLISHERS'

Write-Host ''
if ($script:fail -eq 0) {
    Write-Host "RESULT: PASS  ($script:pass catalog checks)" -ForegroundColor Green
    exit 0
} else {
    Write-Host "RESULT: FAIL  ($script:fail failed, $script:pass passed)" -ForegroundColor Red
    exit 1
}
